name: Scheduled healthcheck

on:
  schedule:
    - cron: '5-45 * * * *'

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health